# .github/workflows/docker-build-and-push.yml

name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/message-publish:${{ github.run_number }}
          #               ^ Docker Hub 사용자 이름      ^ 이미지 이름    ^ 고유한 실행 ID를 태그로 사용
          cache-from: type=gha
          cache-to: type=gha,mode=max
